name: Weekly Episode

permissions:
  contents: write         # so the workflow can push if you keep that step

on:
  schedule:
    - cron: '0 14 * * MON'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      ARXIV_LOOKBACK_DAYS: 365
      ARXIV_MAX_RESULTS: 50
    steps:
      - uses: actions/checkout@v4

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: python src/make_episode.py

      # Remove this entire step if you don't need to push anything any more
      # - name: Commit feed or other artifacts (optional)
      #   run: |
      #     git config --global user.email "bot@example.com"
      #     git config --global user.name "Episode-Bot"
      #     git add .
      #     git commit -m "Auto-update" || echo "no changes"
      #     git push
